### ISSUE TITLE
M1600 Yaml params file

### ISSUE THREAD

**Issue by richarJ2002** [mbiselx/velarray#2]
It would seem instead of comitting the m1600.yaml file in the config folder you've committed a simlink directory instead. Could you add the correct yaml file or at least point in the direction to where you found it?

**Comment by mbiselx** [comment]
Thanks for pointing this out. 
The YAML file was created by me, using the same format as the [ros-drivers/velodyne](https://github.com/ros-drivers/velodyne/tree/master/velodyne_pointcloud/params) project and some manual calculations.
